### ISSUE TITLE
Add Collection Generator

### ISSUE THREAD

**Issue by wildintellect** [developmentseed/cop-dem#1]
**Is your feature request related to a problem? Please describe.**
Current code only generates items, does not generate a Collection STAC json.

**Describe the solution you'd like**
A a second command to generate the Collection template than can be easily amended based on final host of the data. Should have a flag for glo30 vs glo90.

**Describe alternatives you've considered**
Not adding to the codebase

**Comment by wildintellect** [comment]
@bitner @jjfrench could you review these STAC records to make sure I haven't missed anything.

One thing I'm not happy about is the line endings in the description. Open to suggestions on a better way to do it, so that clients can choose to wrap that however they like.

[STAC_samples.zip](https://github.com/developmentseed/cop-dem/files/10061642/STAC_samples.zip)

**Comment by jjfrench** [comment]
Just a few questions about the _Feature_ record
- Is Sinergise supposed to have two separate provider objects?
- Is there a `collection` link that can be added?
- Could the `handbook` and `license` links go into the _Collection_ records?

**Comment by wildintellect** [comment]
@jjfrench 
1. this is why that happened https://github.com/developmentseed/cop-dem/issues/3, if you can think of logic to inject HOST to and existing Provider easily I'm listening.
2. can you clarify where you expect a `collection` link?
3. good point, I think I missed adding those links to collection, will add - need to find a better link than the SDSC handbook link.

**Comment by jjfrench** [comment]
Oh sorry, not a `collection` link, just a `collection` keyword saying what collection it belongs to. I'll take a look at https://github.com/developmentseed/cop-dem/issues/3

**Comment by wildintellect** [comment]
@jjfrench We're talking about on the STAC `item` to specify collection?

**Comment by bitner** [comment]
> @bitner @jjfrench could you review these STAC records to make sure I haven't missed anything.
> 
> One thing I'm not happy about is the line endings in the description. Open to suggestions on a better way to do it, so that clients can choose to wrap that however they like.
> 
> [STAC_samples.zip](https://github.com/developmentseed/cop-dem/files/10061642/STAC_samples.zip)

You should just provide the description with no carriage returns at all.

**Comment by bitner** [comment]
> @jjfrench We're talking about on the STAC `item` to specify collection?

Yes, items require a "collection" keyword with the id of the collection (in pgstac, this is a foreign key to the collections table, so the collection must exist before an item for that collection is added).

**Comment by bitner** [comment]
You can run items/collections through https://staclint.com/ to help validate

**Comment by wildintellect** [comment]
@jjfrench here is the updated samples, after making the fixes suggested above.  See also #4 PR which should be ready now.
[STAC_samples_1.zip](https://github.com/developmentseed/cop-dem/files/10071825/STAC_samples_1.zip)

**Comment by wildintellect** [comment]
Draft PR back to main fork opened https://github.com/stactools-packages/cop-dem/issues/7
Will close this once that PR is resolved.

**Comment by wildintellect** [comment]
I've updated the PR, including bumping the python version as `:=` needs 3.8
@chuckwondo @jjfrench any idea why it's still expecting python 3.7 in the CI workflow 


![Image](https://user-images.githubusercontent.com/306179/207999099-a1a10249-c9d9-40fd-9604-11513170ac28.png)

**Comment by chuckwondo** [comment]
@wildintellect it might be a red herring. First fix the problem with the 3.10 tests, then perhaps that will go away: https://github.com/stactools-packages/cop-dem/actions/runs/3709340869/jobs/6287859730

**Comment by wildintellect** [comment]
PR is passing now, I consider this done as the rest relies on the cop-dem maintainers.
